from __future__ import annotations

import asyncio
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from diving_fish_b50_mcp.server import DivingFishError
from maimaidx_render_mcp import server as render_server
from maimaidx_render_mcp.maimaidx import maimaidx_music_info, maimaidx_player_score, maimaidx_update_table
from maimaidx_render_mcp.maimaidx import image as image_module
from maimaidx_render_mcp.maimaidx import mai
from maimaidx_render_mcp.maimaidx.image import music_picture
from maimaidx_render_mcp.maimaidx.maimaidx_error import TokenNotFoundError
from maimaidx_render_mcp.maimaidx.maimaidx_model import Data, PlayInfoDefault, UserInfo
from maimaidx_render_mcp.shim.mai_music import MusicList
from maimaidx_render_mcp.shim.mai_api import maiApi


class MaimaidxRenderRecordsTests(unittest.TestCase):
    def test_credit_text_uses_ling(self) -> None:
        from maimaidx_render_mcp.maimaidx import BOTNAME, CREDIT_TEXT

        self.assertEqual(BOTNAME, "MaiBot")
        self.assertEqual(CREDIT_TEXT, "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by MaiBot")

    def test_query_user_computed_b50_uses_computed_total_as_display_rating(self) -> None:
        b50 = {
            "player": {"nickname": "Tester", "rating": 9999, "additionalRating": 0, "plate": "舞舞"},
            "ratingBreakdown": {"sd": 596, "dx": 280, "total": 876},
            "charts": {
                "sd": [
                    {
                        "songId": 1001,
                        "title": "Old Song",
                        "type": "DX",
                        "level": "13+",
                        "levelLabel": "Master",
                        "levelIndex": 3,
                        "ds": 13.7,
                        "fitDiff": 13.5,
                        "achievements": 100.0,
                        "dxScore": 1000,
                        "ra": 300,
                        "fittedRa": 292,
                        "ratingBase": "fitDiff",
                        "rate": "sss",
                    },
                    {
                        "songId": 1003,
                        "title": "Better Old Song",
                        "type": "DX",
                        "level": "14",
                        "levelLabel": "Master",
                        "levelIndex": 3,
                        "ds": 14.0,
                        "fitDiff": 14.1,
                        "achievements": 100.0,
                        "dxScore": 1200,
                        "ra": 310,
                        "fittedRa": 304,
                        "ratingBase": "fitDiff",
                        "rate": "sss",
                    }
                ],
                "dx": [
                    {
                        "songId": 1002,
                        "title": "New Song",
                        "type": "DX",
                        "level": "14",
                        "levelLabel": "Master",
                        "levelIndex": 3,
                        "ds": 14.0,
                        "fitDiff": 13.0,
                        "achievements": 100.0,
                        "dxScore": 1100,
                        "ra": 310,
                        "fittedRa": 280,
                        "ratingBase": "fitDiff",
                        "rate": "sss",
                    }
                ],
            },
            "source": "diving-fish-records",
        }

        with patch("diving_fish_b50_mcp.server.query_computed_b50", return_value=b50):
            user = asyncio.run(maiApi.query_user_computed_b50(qqid=123456))

        self.assertEqual(user.rating, 876)
        self.assertEqual(user.nickname, "Tester")
        self.assertEqual(len(user.charts.sd), 2)
        self.assertEqual(len(user.charts.dx), 1)
        self.assertEqual([chart.song_id for chart in user.charts.sd], [1003, 1001])
        self.assertEqual(user.charts.sd[0].ds, 14.1)
        self.assertEqual(user.charts.sd[0].ra, 304)
        self.assertEqual(user.charts.sd[1].ds, 13.5)
        self.assertEqual(user.charts.sd[1].ra, 292)
        self.assertEqual(user.charts.dx[0].ds, 13.0)
        self.assertEqual(user.charts.dx[0].ra, 280)

    def test_render_music_lookup_accepts_waterfish_dx_offset_id(self) -> None:
        mai._ensure_loaded()

        music = mai.total_list.by_id("11475")

        self.assertIsNotNone(music)
        assert music is not None
        self.assertEqual(music.id, "11475")
        self.assertEqual(music.title, "SUPER AMBULANCE")

    def test_render_music_filter_supports_rise_score_query_shape(self) -> None:
        mai._ensure_loaded()

        songs = mai.total_list.filter(
            level=None,
            ds=(14.0, 15.0),
            version=["maimai でらっくす PRiSM"],
        )

        self.assertGreater(len(songs), 0)
        self.assertTrue(all(song.diff for song in songs))
        self.assertTrue(
            all(
                any(14.0 <= song.ds[index] <= 15.0 for index in song.diff)
                for song in songs
            )
        )

    def test_rating_level_data_uses_drawable_constant_keys(self) -> None:
        mai._ensure_loaded()

        level_14 = mai.total_level_data["14"]
        level_14_plus = mai.total_level_data["14+"]

        self.assertIn("14.0", level_14)
        self.assertNotIn("14.0.0", level_14)
        self.assertEqual(list(level_14_plus.keys()), ["14.9", "14.8", "14.7", "14.6"])
        self.assertNotIn("14.0.9", level_14_plus)
        self.assertGreater(sum(len(songs) for songs in level_14.values()), 0)

    def test_rating_background_keeps_nonnumeric_song_labels(self) -> None:
        self.assertEqual(maimaidx_update_table._display_song_id("11475"), "11475")
        self.assertEqual(maimaidx_update_table._song_id_label("Maboroshi"), ("Maboroshi", False))
        self.assertEqual(maimaidx_update_table._song_id_label("白色リリィ"), ("白色リリィ", False))

    def test_score_list_uses_waterfish_dx_offset_id_for_local_metadata(self) -> None:
        record = PlayInfoDefault(
            id=11475,
            title="SUPER AMBULANCE",
            type="DX",
            level="14",
            level_index=3,
            ds=0,
            achievements=100.5,
        )

        song_id = maimaidx_player_score._fill_default_record_from_music(record)

        self.assertEqual(song_id, "11475")
        self.assertEqual(record.ds, 14.3)
        self.assertEqual(record.level, "14")
        self.assertGreater(record.ra, 0)

    def test_query_user_b50_normalizes_empty_bonus_markers(self) -> None:
        result = {
            "player": {"nickname": "Tester", "rating": 15000},
            "charts": {
                "sd": [
                    {
                        "songId": 8,
                        "title": "True Love Song",
                        "type": "SD",
                        "level": "12",
                        "levelLabel": "Master",
                        "levelIndex": 3,
                        "ds": 12.4,
                        "achievements": 100.0,
                        "dxScore": 1234,
                        "fc": None,
                        "fs": "None",
                        "ra": 250,
                        "rate": "sss",
                    }
                ],
                "dx": [],
            },
        }
        calls: list[dict[str, object]] = []

        def fake_query_b50(arguments):
            calls.append(arguments)
            return result

        with patch("diving_fish_b50_mcp.server.query_b50", side_effect=fake_query_b50):
            user = asyncio.run(maiApi.query_user_b50(qqid=123456))

        chart = user.charts.sd[0]
        self.assertEqual(chart.fc, "")
        self.assertEqual(chart.fs, "")
        self.assertEqual(chart.rate, "sss")
        self.assertEqual(
            calls,
            [{"qq": "123456", "includeChartMetadata": True, "timeoutMs": 30000}],
        )

    def test_query_user_plate_preserves_song_id(self) -> None:
        result = {
            "records": [
                {
                    "songId": 11753,
                    "title": "Test Song",
                    "type": "DX",
                    "level": "13",
                    "levelIndex": 3,
                    "ds": 13.0,
                    "achievements": 100.5,
                    "dxScore": 1234,
                    "fc": "fc",
                    "fs": "",
                    "ra": 300,
                    "rate": "sss",
                }
            ]
        }

        calls: list[dict[str, object]] = []

        def fake_query_maimai_player_records(arguments):
            calls.append(arguments)
            return result

        with patch("diving_fish_b50_mcp.server.query_maimai_player_records", side_effect=fake_query_maimai_player_records):
            records = asyncio.run(maiApi.query_user_plate(qqid=123456))

        self.assertEqual(len(records), 1)
        self.assertEqual(records[0].song_id, 11753)
        self.assertEqual(records[0].level_index, 3)
        self.assertEqual(calls, [{"qq": "123456", "timeoutMs": 30000}])

    def test_query_user_plate_normalizes_empty_bonus_markers(self) -> None:
        result = {
            "records": [
                {
                    "songId": 11753,
                    "title": "Test Song",
                    "type": "DX",
                    "level": "13",
                    "levelIndex": 3,
                    "ds": 13.0,
                    "achievements": 100.5,
                    "dxScore": 1234,
                    "fc": "None",
                    "fs": None,
                    "ra": 300,
                    "rate": None,
                }
            ]
        }

        with patch("diving_fish_b50_mcp.server.query_maimai_player_records", return_value=result):
            records = asyncio.run(maiApi.query_user_plate(qqid=123456))

        self.assertEqual(records[0].fc, "")
        self.assertEqual(records[0].fs, "")
        self.assertEqual(records[0].rate, "d")

    def test_query_user_post_dev_normalizes_empty_bonus_markers(self) -> None:
        result = {
            "records": [
                {
                    "songId": 11753,
                    "title": "Test Song",
                    "type": "DX",
                    "level": "13",
                    "levelLabel": "Master",
                    "levelIndex": 3,
                    "ds": 13.0,
                    "achievements": 100.5,
                    "dxScore": 1234,
                    "fc": None,
                    "fs": "null",
                    "ra": 300,
                    "rate": None,
                }
            ]
        }

        with patch("diving_fish_b50_mcp.server.query_maimai_song_score", return_value=result):
            records = asyncio.run(maiApi.query_user_post_dev(qqid=123456, music_id=11753))

        self.assertEqual(records[0].fc, "")
        self.assertEqual(records[0].fs, "")
        self.assertEqual(records[0].rate, "d")

    def test_query_user_plate_does_not_silently_drop_auth_errors(self) -> None:
        error = DivingFishError("该接口需要 Developer-Token。", code="AUTH_REQUIRED")

        with patch("diving_fish_b50_mcp.server.query_maimai_player_records", side_effect=error):
            with self.assertRaises(TokenNotFoundError):
                asyncio.run(maiApi.query_user_plate(qqid=123456))

    def test_full_record_render_fallbacks_do_not_pass_all_version_filter(self) -> None:
        calls: list[dict[str, object]] = []

        async def fake_query_user_plate(**kwargs):
            calls.append(kwargs)
            raise RuntimeError("stop after capturing query_user_plate arguments")

        async def fake_query_user_b50(**_kwargs):
            return UserInfo(
                additional_rating=0,
                nickname="Tester",
                username=None,
                rating=15000,
                charts=Data(sd=[], dx=[]),
            )

        with patch.dict(os.environ, {"DIVING_FISH_DEVELOPER_TOKEN": ""}):
            with patch.object(maiApi, "query_user_plate", new=fake_query_user_plate):
                with patch.object(maimaidx_music_info.log, "error", new=lambda *_args, **_kwargs: None):
                    with patch.object(maimaidx_player_score.log, "error", new=lambda *_args, **_kwargs: None):
                        asyncio.run(maimaidx_music_info.draw_music_play_data(123456, "8"))
                        asyncio.run(maimaidx_music_info.draw_rating_table(123456, "14"))
                        asyncio.run(maimaidx_player_score.level_process_data(123456, None, "14", "sss"))
                        asyncio.run(maimaidx_player_score.level_achievement_list_data(123456, None, "14"))
                        with patch.object(maiApi, "query_user_b50", new=fake_query_user_b50):
                            asyncio.run(maimaidx_player_score.rise_score_data(123456))

        self.assertEqual(len(calls), 5)
        for kwargs in calls:
            self.assertNotIn("version", kwargs)

    def test_render_level_tools_normalize_numeric_level_arguments(self) -> None:
        captured: dict[str, object] = {}
        rating_calls: list[tuple[int | None, str | object, bool, str | None]] = []

        async def fake_level_process(qqid, username, level, plan, category="default", page=1, server="cn"):
            captured["progress"] = level
            captured["progress_server"] = server
            return ""

        async def fake_rating_table(qqid, rating, isfc=False, username=None):
            rating_calls.append((qqid, rating, isfc, username))
            return ""

        async def fake_rise_score(qqid, username=None, level=None, score=None, algorithm="legacy"):
            captured["rise"] = level
            captured["rise_algorithm"] = algorithm
            return ""

        with patch.object(render_server, "_level_process_data", new=fake_level_process):
            render_server._render_progress({"qq": "123456", "level": 15})
            self.assertEqual(captured["progress_server"], "cn")
            jp_result = render_server._render_progress({"qq": "123456", "level": 15, "server": "jp"})
            self.assertTrue(jp_result.get("isError"))
            self.assertIn("不支持日服/dxdata", jp_result["content"][0]["text"])
        with patch.object(render_server, "_draw_rating_table", new=fake_rating_table):
            render_server._render_rating({"qq": "123456", "rating": 15})
            render_server._render_rating({"username": "alice", "rating": "14+"})
        with patch.object(render_server, "_rise_score_data", new=fake_rise_score):
            render_server._render_rise_score({"qq": "123456", "level": 15})

        self.assertEqual(captured["progress"], "15")
        self.assertEqual(captured["progress_server"], "cn")
        self.assertEqual(rating_calls, [(123456, "15", False, None), (None, "14+", False, "alice")])
        self.assertEqual(captured["rise"], "15")
        self.assertEqual(captured["rise_algorithm"], "legacy")

    def test_level_progress_accepts_numeric_level_in_internal_renderer(self) -> None:
        captured: dict[str, int] = {}
        old_loaded = mai._loaded
        old_total_list = mai.total_list
        old_plate_id_list = mai.total_plate_id_list
        old_level_data = mai.total_level_data

        async def fake_query_user_plate(**_kwargs):
            return []

        class FakeDrawScore:
            def __init__(self, image):
                self._im = image

            def draw_plan(self, completed, completed_y, unfinished, unfinished_y, notplayed, plan, completed_len):
                captured["notplayed"] = len(notplayed)
                return self._im

        try:
            mai._loaded = False
            mai.total_list = MusicList()
            mai.total_plate_id_list = {}
            mai.total_level_data = {}
            with patch.dict(os.environ, {"DIVING_FISH_DEVELOPER_TOKEN": ""}):
                with patch.object(maiApi, "query_user_plate", new=fake_query_user_plate):
                    with patch.object(maimaidx_player_score, "DrawScore", new=FakeDrawScore):
                        asyncio.run(maimaidx_player_score.level_process_data(123456, None, 15, "sss"))
        finally:
            mai._loaded = old_loaded
            mai.total_list = old_total_list
            mai.total_plate_id_list = old_plate_id_list
            mai.total_level_data = old_level_data

        self.assertGreater(captured["notplayed"], 0)

    def test_numeric_cover_lookup_prefers_id_cover(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            cover_root = Path(tempdir)
            (cover_root / "123.png").write_bytes(b"id-cover")

            with patch.object(image_module, "coverdir", cover_root):
                self.assertEqual(music_picture("123").name, "123.png")


if __name__ == "__main__":
    unittest.main()
