use std::{io::Cursor, path::Path};

use image::{
    ColorType, ImageEncoder, Rgba, RgbaImage,
    codecs::png::PngEncoder,
    imageops::{FilterType, crop_imm, overlay, resize},
};

use super::{
    RiseScoreRenderError, RiseScoreRenderedPng, RiseScoreView,
    assets::RiseScoreAssets,
    card::RiseScoreCardDrawer,
    layout::{CROP_LEFT, OUTPUT_WIDTH, card_origin, draw_centered, gradient},
};
use crate::CoverResolver;

const TEXT_COLOR: Rgba<u8> = Rgba([124, 129, 255, 255]);

pub struct RiseScoreRenderer {
    assets: RiseScoreAssets,
    covers: CoverResolver,
}

impl RiseScoreRenderer {
    pub fn new(
        static_root: impl AsRef<Path>,
        cover_cache_root: impl AsRef<Path>,
    ) -> Result<Self, RiseScoreRenderError> {
        Ok(Self {
            assets: RiseScoreAssets::load(static_root.as_ref())?,
            covers: CoverResolver::new(static_root.as_ref(), cover_cache_root.as_ref()),
        })
    }

    pub fn render(
        &self,
        view: &RiseScoreView,
    ) -> Result<RiseScoreRenderedPng, RiseScoreRenderError> {
        view.validate()?;
        let height = view.height();
        let mut image = gradient(height);
        self.draw_background(&mut image);
        self.draw_headers(&mut image);
        let cards = RiseScoreCardDrawer::new(&self.assets, &self.covers);
        let mut placeholder_covers = 0;
        for (index, item) in view.legacy.iter().enumerate() {
            placeholder_covers +=
                usize::from(cards.draw(&mut image, card_origin(false, index), item)?);
        }
        for (index, item) in view.current.iter().enumerate() {
            placeholder_covers +=
                usize::from(cards.draw(&mut image, card_origin(true, index), item)?);
        }
        self.draw_footer(&mut image);
        encode(crop_canvas(&image), placeholder_covers)
    }

    fn draw_background(&self, image: &mut RgbaImage) {
        overlay(
            image,
            &resize(&self.assets.aurora, 1_400, 220, FilterType::Lanczos3),
            0,
            0,
        );
        overlay(image, &self.assets.shines, 34, 0);
        overlay(
            image,
            &self.assets.rainbow,
            319,
            i64::from(image.height().saturating_sub(643)),
        );
        overlay(
            image,
            &resize(
                &self.assets.rainbow_bottom,
                1_200,
                200,
                FilterType::Lanczos3,
            ),
            100,
            i64::from(image.height().saturating_sub(343)),
        );
        let mut y = 0_u32;
        while y < image.height() {
            overlay(image, &self.assets.pattern, 0, i64::from(y));
            y = y.saturating_add(365);
        }
    }

    fn draw_headers(&self, image: &mut RgbaImage) {
        let title = resize(&self.assets.title, 273, 80, FilterType::Lanczos3);
        overlay(image, &title, 314, 30);
        overlay(image, &title, 814, 30);
        draw_centered(
            image,
            450,
            68,
            "旧版本谱面推荐",
            26.0,
            TEXT_COLOR,
            &self.assets.bold,
        );
        draw_centered(
            image,
            950,
            68,
            "新版本谱面推荐",
            26.0,
            TEXT_COLOR,
            &self.assets.bold,
        );
    }

    fn draw_footer(&self, image: &mut RgbaImage) {
        let height = image.height();
        overlay(
            image,
            &resize(&self.assets.design, 800, 72, FilterType::Lanczos3),
            300,
            i64::from(height.saturating_sub(110)),
        );
        let credit = footer_text();
        draw_centered(
            image,
            700,
            i32::try_from(height.saturating_sub(76)).unwrap_or(0),
            &credit,
            26.0,
            TEXT_COLOR,
            &self.assets.bold,
        );
    }
}

pub(super) fn footer_text() -> String {
    "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by 铃".to_owned()
}

pub(super) fn crop_canvas(image: &RgbaImage) -> RgbaImage {
    crop_imm(image, CROP_LEFT, 0, OUTPUT_WIDTH, image.height()).to_image()
}

fn encode(
    image: RgbaImage,
    placeholder_covers: usize,
) -> Result<RiseScoreRenderedPng, RiseScoreRenderError> {
    let width = image.width();
    let height = image.height();
    let mut bytes = Vec::new();
    PngEncoder::new(Cursor::new(&mut bytes))
        .write_image(image.as_raw(), width, height, ColorType::Rgba8.into())
        .map_err(crate::RenderError::PngEncode)?;
    Ok(RiseScoreRenderedPng {
        bytes,
        width,
        height,
        placeholder_covers,
    })
}
