use image::{Rgba, RgbaImage};

use super::{
    model::height_for_rows,
    renderer::{crop_canvas, footer_text},
};

#[test]
fn height_matches_legacy_row_formula() {
    assert_eq!(height_for_rows(0), 260);
    assert_eq!(height_for_rows(1), 400);
    assert_eq!(height_for_rows(5), 960);
}

#[test]
fn crop_keeps_exact_legacy_pixel_boundaries() {
    let mut source = RgbaImage::from_pixel(1_400, 3, Rgba([0, 0, 0, 255]));
    source.put_pixel(199, 1, Rgba([10, 0, 0, 255]));
    source.put_pixel(200, 1, Rgba([20, 0, 0, 255]));
    source.put_pixel(1_199, 1, Rgba([30, 0, 0, 255]));
    source.put_pixel(1_200, 1, Rgba([40, 0, 0, 255]));

    let cropped = crop_canvas(&source);

    assert_eq!(cropped.dimensions(), (1_000, 3));
    assert_eq!(cropped.get_pixel(0, 1), &Rgba([20, 0, 0, 255]));
    assert_eq!(cropped.get_pixel(999, 1), &Rgba([30, 0, 0, 255]));
}

#[test]
fn missing_asset_errors_do_not_expose_the_configured_root() {
    let root = std::path::Path::new("/secret-rise-score-assets");
    let error = super::assets::RiseScoreAssets::load(root)
        .err()
        .map(|error| error.to_string());
    assert!(error.as_deref().is_some_and(|text| {
        text.contains("Torus SemiBold.otf") && !text.contains("secret-rise-score-assets")
    }));
}

#[test]
fn rendered_footer_copy_matches_the_frozen_credit() {
    assert_eq!(
        footer_text(),
        "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by 铃"
    );
}
