use std::collections::{BTreeMap, HashSet};

use ab_glyph::FontArc;
use image::{
    Rgba, RgbaImage,
    imageops::{FilterType, overlay, resize},
};
use imageproc::{
    drawing::{draw_filled_rect_mut, text_size},
    rect::Rect,
};
use maimai_core::{AchievementRank, Difficulty, SongIdValue, achievement_rank};

use super::{
    CompletionRenderer, encode,
    model::{
        CompletionRenderedPng, CompletionState, FullComboStatus, FullSyncStatus, PlateMemberView,
        PlateTableKind, PlateTableView,
    },
};
use crate::{
    RenderError,
    cover::ResolvedCover,
    renderer::fill_rounded_rect,
    score_list::layout::gradient,
    text::middle_origin_y,
    text::{draw_text, fit_text},
};

const WIDTH: u32 = 1_400;
const CELL: u32 = 100;
const STEP: u32 = 115;
const COLUMNS: usize = 10;
const ACCENT: Rgba<u8> = Rgba([124, 129, 255, 255]);
const WHITE: Rgba<u8> = Rgba([255, 255, 255, 255]);

impl CompletionRenderer {
    pub fn render_plate(
        &self,
        view: &PlateTableView,
    ) -> Result<CompletionRenderedPng, RenderError> {
        view.validate()?;
        let template = self.assets.plate_template(&template_name(view))?;
        let uses_template = template.is_some();
        let mut image = match template {
            Some(image) => image,
            None => self.generated_plate_background(view)?,
        };
        let mut placeholders = 0;
        for (index, member) in view.members.iter().enumerate() {
            let origin = member_origin(&view.members, index);
            if !uses_template {
                placeholders += usize::from(self.draw_member_cover(&mut image, origin, member)?);
            }
            self.draw_member_state(&mut image, origin, member, &view.target)?;
        }
        self.draw_plate_header(&mut image, view)?;
        let (bytes, width, height) = encode(image)?;
        Ok(CompletionRenderedPng {
            bytes,
            width,
            height,
            placeholder_covers: placeholders,
        })
    }

    fn generated_plate_background(&self, view: &PlateTableView) -> Result<RgbaImage, RenderError> {
        let groups = group_order(&view.members);
        let rows = groups
            .iter()
            .map(|level| group_size(&view.members, level).div_ceil(COLUMNS) as u32)
            .sum::<u32>();
        let height = 510 + rows * STEP + groups.len().saturating_sub(1) as u32 * 15;
        let mut image = gradient(height);
        overlay(
            &mut image,
            &resize(&self.score_assets.aurora, WIDTH, 220, FilterType::Lanczos3),
            0,
            0,
        );
        overlay(&mut image, &self.score_assets.shines, 34, 0);
        overlay(
            &mut image,
            &self.score_assets.rainbow,
            319,
            i64::from(height.saturating_sub(643)),
        );
        overlay(
            &mut image,
            &resize(
                &self.score_assets.rainbow_bottom,
                1_200,
                200,
                FilterType::Lanczos3,
            ),
            100,
            i64::from(height.saturating_sub(343)),
        );
        for y in (0..height).step_by(365) {
            overlay(&mut image, &self.score_assets.pattern, 0, i64::from(y));
        }
        overlay(
            &mut image,
            &self.score_assets.design,
            200,
            i64::from(height.saturating_sub(113)),
        );
        centered_text(
            &mut image,
            (700, i32::try_from(height).unwrap_or(i32::MAX) - 70),
            "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by 铃",
            26.0,
            ACCENT,
            &self.assets.bold,
        );
        let badge = self.assets.pic("UI_CMN_Chara_Level_S_01.png")?;
        for (group_index, level) in groups.iter().enumerate() {
            let y = 375
                + rows_before(&view.members, level) as i32 * STEP as i32
                + group_index as i32 * 15;
            overlay(&mut image, &badge, 65, i64::from(y));
            centered_text(
                &mut image,
                (113, y + 49),
                level,
                42.0,
                Rgba([54, 60, 90, 255]),
                &self.assets.regular,
            );
        }
        Ok(image)
    }

    fn draw_member_cover(
        &self,
        image: &mut RgbaImage,
        origin: (i32, i32),
        member: &PlateMemberView,
    ) -> Result<bool, RenderError> {
        let (cover, placeholder) = match self
            .covers
            .resolve_music(Some(&member.cover_id), member.image_name.as_deref())?
        {
            ResolvedCover::Image(image) => (image, false),
            ResolvedCover::Missing(_) => (
                RgbaImage::from_pixel(CELL, CELL, Rgba([224, 229, 245, 255])),
                true,
            ),
        };
        overlay(
            image,
            &resize(&cover, CELL, CELL, FilterType::Lanczos3),
            i64::from(origin.0),
            i64::from(origin.1),
        );
        draw_filled_rect_mut(
            image,
            Rect::at(origin.0, origin.1 + 80).of_size(CELL, 20),
            ACCENT,
        );
        centered_text(
            image,
            (origin.0 + 50, origin.1 + 89),
            &fit_text(
                &display_id(&member.cover_id),
                96,
                24.0,
                &self.assets.regular,
            ),
            24.0,
            WHITE,
            &self.assets.regular,
        );
        Ok(placeholder)
    }

    fn draw_member_state(
        &self,
        image: &mut RgbaImage,
        origin: (i32, i32),
        member: &PlateMemberView,
        target: &str,
    ) -> Result<(), RenderError> {
        let master = member
            .charts
            .iter()
            .find(|chart| chart.difficulty == Difficulty::Master);
        if let Some(state) = master
            .map(|chart| chart.state)
            .filter(|state| state.completed)
        {
            overlay(
                image,
                &self.assets.pic("complete_bg_2.png")?,
                i64::from(origin.0),
                i64::from(origin.1),
            );
            if let Some(asset) = plate_state_asset(target, state)
                && let Some(icon) = self.assets.optional_pic(asset)?
            {
                let (size, offset) = if target == "将" {
                    ((102, 46), (-1, 15))
                } else {
                    ((75, 75), (13, 3))
                };
                overlay(
                    image,
                    &resize(&icon, size.0, size.1, FilterType::Lanczos3),
                    i64::from(origin.0 + offset.0),
                    i64::from(origin.1 + offset.1),
                );
            }
        }
        for chart in &member.charts {
            let Some(index) = difficulty_index(chart.difficulty) else {
                continue;
            };
            if !chart.state.completed || index >= 4 {
                continue;
            }
            overlay(
                image,
                &self.assets.pic(&format!("t-{index}.png"))?,
                i64::from(origin.0 + 5 + index as i32 * 25),
                i64::from(origin.1 + 67),
            );
        }
        Ok(())
    }

    fn draw_plate_header(
        &self,
        image: &mut RgbaImage,
        view: &PlateTableView,
    ) -> Result<(), RenderError> {
        overlay(image, &self.assets.pic("plate_num.png")?, 185, 20);
        let title_name = format!("{}{}", view.version, plan_title(&view.target));
        let title = self.assets.plate_title(&title_name)?.map_or_else(
            || fallback_title(&title_name, &self.assets.bold),
            |image| resize(&image, 1_000, 161, FilterType::Lanczos3),
        );
        overlay(image, &title, 200, 35);

        let difficulties = required_difficulties(&view.version);
        let counts = difficulties
            .iter()
            .map(|difficulty| completed_count(&view.members, *difficulty))
            .collect::<Vec<_>>();
        let all = view
            .members
            .iter()
            .filter(|member| {
                difficulties.iter().all(|difficulty| {
                    member
                        .charts
                        .iter()
                        .any(|chart| chart.difficulty == *difficulty && chart.state.completed)
                })
            })
            .count();
        let mut values = vec![(format!("{all}/{}", view.declared_song_count), ACCENT)];
        values.extend(counts.into_iter().enumerate().map(|(index, count)| {
            let value = if count == view.declared_song_count {
                "完成".to_owned()
            } else {
                count.to_string()
            };
            (value, difficulty_color(difficulties[index]))
        }));
        for (index, (value, color)) in values.into_iter().enumerate() {
            right_stroked_text(
                image,
                (390 + index as i32 * 200, 270),
                &value,
                if value == "完成" { 42.0 } else { 48.0 },
                color,
                if value == "完成" {
                    &self.assets.bold
                } else {
                    &self.assets.regular
                },
                4,
            );
        }
        Ok(())
    }
}

fn fallback_title(title: &str, font: &FontArc) -> RgbaImage {
    let mut image = RgbaImage::new(1_000, 161);
    fill_rounded_rect(&mut image, (18, 17, 982, 144), 24, ACCENT);
    fill_rounded_rect(
        &mut image,
        (24, 23, 976, 138),
        18,
        Rgba([255, 255, 255, 218]),
    );
    fill_rounded_rect(
        &mut image,
        (34, 33, 966, 128),
        18,
        Rgba([193, 247, 225, 255]),
    );
    fill_rounded_rect(
        &mut image,
        (37, 36, 963, 125),
        15,
        Rgba([255, 255, 255, 218]),
    );
    let mut size = 98.0;
    while size > 52.0 && text_size(size, font, title).0 > 850 {
        size -= 4.0;
    }
    centered_stroked_text(&mut image, (500, 80), title, size, ACCENT, font, 5);
    image
}

fn plate_state_asset(target: &str, state: CompletionState) -> Option<&'static str> {
    match target {
        "极" | "極" | "神" => match state.combo? {
            FullComboStatus::FullCombo => Some("UI_CHR_PlayBonus_FC.png"),
            FullComboStatus::FullComboPlus => Some("UI_CHR_PlayBonus_FCp.png"),
            FullComboStatus::AllPerfect => Some("UI_CHR_PlayBonus_AP.png"),
            FullComboStatus::AllPerfectPlus => Some("UI_CHR_PlayBonus_APp.png"),
        },
        "舞舞" => match state.sync? {
            FullSyncStatus::FullSync => Some("UI_CHR_PlayBonus_FS.png"),
            FullSyncStatus::FullSyncPlus => Some("UI_CHR_PlayBonus_FSp.png"),
            FullSyncStatus::FullSyncDeluxe => Some("UI_CHR_PlayBonus_FSD.png"),
            FullSyncStatus::FullSyncDeluxePlus => Some("UI_CHR_PlayBonus_FSDp.png"),
        },
        "将" => state.achievement.map(rank_asset),
        _ => None,
    }
}

fn rank_asset(value: maimai_core::AchievementRate) -> &'static str {
    match achievement_rank(value) {
        AchievementRank::D => "UI_TTR_Rank_D.png",
        AchievementRank::C => "UI_TTR_Rank_C.png",
        AchievementRank::B => "UI_TTR_Rank_B.png",
        AchievementRank::Bb => "UI_TTR_Rank_BB.png",
        AchievementRank::Bbb => "UI_TTR_Rank_BBB.png",
        AchievementRank::A => "UI_TTR_Rank_A.png",
        AchievementRank::Aa => "UI_TTR_Rank_AA.png",
        AchievementRank::Aaa => "UI_TTR_Rank_AAA.png",
        AchievementRank::S => "UI_TTR_Rank_S.png",
        AchievementRank::SPlus => "UI_TTR_Rank_Sp.png",
        AchievementRank::Ss => "UI_TTR_Rank_SS.png",
        AchievementRank::SsPlus => "UI_TTR_Rank_SSp.png",
        AchievementRank::Sss => "UI_TTR_Rank_SSS.png",
        AchievementRank::SssPlus => "UI_TTR_Rank_SSSp.png",
    }
}

fn member_origin(members: &[PlateMemberView], target: usize) -> (i32, i32) {
    let member = &members[target];
    let groups = group_order(members);
    let group_index = groups
        .iter()
        .position(|level| level == &member.master_level)
        .unwrap_or(0);
    let within = members[..target]
        .iter()
        .filter(|value| value.master_level == member.master_level)
        .count();
    (
        200 + (within % COLUMNS) as i32 * STEP as i32,
        375 + (rows_before(members, &member.master_level) + within / COLUMNS) as i32 * STEP as i32
            + group_index as i32 * 15,
    )
}

fn group_order(members: &[PlateMemberView]) -> Vec<String> {
    let mut seen = HashSet::new();
    members
        .iter()
        .filter_map(|member| {
            seen.insert(member.master_level.clone())
                .then_some(member.master_level.clone())
        })
        .collect()
}

fn group_size(members: &[PlateMemberView], level: &str) -> usize {
    members
        .iter()
        .filter(|member| member.master_level == level)
        .count()
}

fn rows_before(members: &[PlateMemberView], target: &str) -> usize {
    let mut groups = BTreeMap::<String, usize>::new();
    for member in members {
        *groups.entry(member.master_level.clone()).or_default() += 1;
    }
    group_order(members)
        .iter()
        .take_while(|level| level.as_str() != target)
        .map(|level| groups[level].div_ceil(COLUMNS))
        .sum()
}

fn required_difficulties(version: &str) -> Vec<Difficulty> {
    let mut values = vec![
        Difficulty::Basic,
        Difficulty::Advanced,
        Difficulty::Expert,
        Difficulty::Master,
    ];
    if matches!(version, "霸" | "舞") {
        values.push(Difficulty::ReMaster);
    }
    values
}

fn completed_count(members: &[PlateMemberView], difficulty: Difficulty) -> usize {
    members
        .iter()
        .filter(|member| {
            member
                .charts
                .iter()
                .any(|chart| chart.difficulty == difficulty && chart.state.completed)
        })
        .count()
}

fn template_name(view: &PlateTableView) -> String {
    match view.kind {
        PlateTableKind::China => view.version.clone(),
        PlateTableKind::Japan => format!("jp_{}", view.version),
        PlateTableKind::Custom => format!("custom_{}", view.version),
    }
}

fn plan_title(value: &str) -> &str {
    if matches!(value, "极" | "極") {
        "極"
    } else {
        value
    }
}

fn display_id(value: &SongIdValue) -> String {
    match value {
        SongIdValue::Numeric(value) => value.to_string(),
        SongIdValue::Text(value) => value.as_str().to_owned(),
    }
}

fn difficulty_index(value: Difficulty) -> Option<usize> {
    match value {
        Difficulty::Basic => Some(0),
        Difficulty::Advanced => Some(1),
        Difficulty::Expert => Some(2),
        Difficulty::Master => Some(3),
        Difficulty::ReMaster => Some(4),
        Difficulty::Utage => None,
    }
}

fn difficulty_color(value: Difficulty) -> Rgba<u8> {
    match value {
        Difficulty::Basic => Rgba([74, 202, 109, 255]),
        Difficulty::Advanced => Rgba([245, 190, 53, 255]),
        Difficulty::Expert => Rgba([239, 77, 91, 255]),
        Difficulty::Master => Rgba([157, 84, 210, 255]),
        Difficulty::ReMaster => Rgba([214, 198, 229, 255]),
        Difficulty::Utage => Rgba([220, 92, 182, 255]),
    }
}

fn centered_text(
    image: &mut RgbaImage,
    center: (i32, i32),
    text: &str,
    size: f32,
    color: Rgba<u8>,
    font: &FontArc,
) {
    let (width, _) = text_size(size, font, text);
    draw_text(
        image,
        (
            center.0 - i32::try_from(width).unwrap_or(i32::MAX) / 2,
            middle_origin_y(center.1, text, size, font),
        ),
        text,
        size,
        color,
        font,
    );
}

fn centered_stroked_text(
    image: &mut RgbaImage,
    center: (i32, i32),
    text: &str,
    size: f32,
    color: Rgba<u8>,
    font: &FontArc,
    stroke: i32,
) {
    let (width, _) = text_size(size, font, text);
    stroked_text(
        image,
        (
            center.0 - i32::try_from(width).unwrap_or(i32::MAX) / 2,
            middle_origin_y(center.1, text, size, font),
        ),
        text,
        size,
        color,
        font,
        stroke,
    );
}

fn right_stroked_text(
    image: &mut RgbaImage,
    anchor: (i32, i32),
    text: &str,
    size: f32,
    color: Rgba<u8>,
    font: &FontArc,
    stroke: i32,
) {
    let (width, _) = text_size(size, font, text);
    stroked_text(
        image,
        (
            anchor.0 - i32::try_from(width).unwrap_or(i32::MAX),
            middle_origin_y(anchor.1, text, size, font),
        ),
        text,
        size,
        color,
        font,
        stroke,
    );
}

#[allow(clippy::too_many_arguments)]
fn stroked_text(
    image: &mut RgbaImage,
    origin: (i32, i32),
    text: &str,
    size: f32,
    color: Rgba<u8>,
    font: &FontArc,
    stroke: i32,
) {
    for dy in -stroke..=stroke {
        for dx in -stroke..=stroke {
            if dx != 0 || dy != 0 {
                draw_text(
                    image,
                    (origin.0 + dx, origin.1 + dy),
                    text,
                    size,
                    WHITE,
                    font,
                );
            }
        }
    }
    draw_text(image, origin, text, size, color, font);
}
