use std::{io::Cursor, path::Path};

use ab_glyph::FontArc;
use image::{
    ColorType, ImageEncoder, Rgba, RgbaImage,
    codecs::png::PngEncoder,
    imageops::{FilterType, overlay, resize},
};
use imageproc::drawing::text_size;
use maimai_core::{ChartGeneration, Difficulty, FullComboStatus, FullSyncStatus};

use super::{
    assets::MusicScoreAssets,
    model::{MusicScoreRenderedPng, MusicScoreRow, MusicScoreView},
};
use crate::{
    CoverResolver, RenderError,
    cover::ResolvedCover,
    text::{draw_text, fit_text, format_constant, format_play_achievement, middle_origin_y},
};

pub(super) const WIDTH: u32 = 1_200;
pub(super) const HEIGHT: u32 = 900;
const INK: Rgba<u8> = Rgba([124, 129, 255, 255]);
const WHITE: Rgba<u8> = Rgba([255, 255, 255, 255]);
#[cfg(test)]
const ROW_X: i32 = 500;
#[cfg(test)]
const ROW_WIDTH: u32 = 600;
const ROW_HEIGHT: u32 = 100;
const ROW_TOP: i32 = 235;
const CREDIT: &str = "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by 铃";

pub struct MusicScoreRenderer {
    assets: MusicScoreAssets,
    covers: CoverResolver,
}

impl MusicScoreRenderer {
    pub fn new(
        static_root: impl AsRef<Path>,
        cover_cache_root: impl AsRef<Path>,
    ) -> Result<Self, RenderError> {
        Ok(Self {
            assets: MusicScoreAssets::load(static_root.as_ref())?,
            covers: CoverResolver::new(static_root.as_ref(), cover_cache_root.as_ref()),
        })
    }

    pub fn render(&self, view: &MusicScoreView) -> Result<MusicScoreRenderedPng, RenderError> {
        let mut image = self.assets.background.clone();
        self.draw_header(&mut image, view)?;
        let (cover, used_placeholder_cover) = self.cover(view)?;
        overlay(
            &mut image,
            &resize(&cover, 300, 300, FilterType::Lanczos3),
            100,
            260,
        );
        if let Some(mask) = self
            .assets
            .optional_pic(&format!("info-{}.png", genre_asset(&view.music.genre)))?
            .or(self.assets.optional_pic("info-maimai.png")?)
        {
            overlay(&mut image, &mask, 100, 260);
        }
        self.draw_rows(&mut image, view)?;
        centered_text(&mut image, (600, 827), CREDIT, 31.5, INK, &self.assets.bold);
        encode(image, used_placeholder_cover)
    }

    #[cfg(test)]
    pub(super) fn credit_text(&self) -> &str {
        CREDIT
    }

    fn draw_header(&self, image: &mut RgbaImage, view: &MusicScoreView) -> Result<(), RenderError> {
        overlay(
            image,
            &resize(
                &self.assets.pic("logo.png")?,
                249,
                120,
                FilterType::Lanczos3,
            ),
            0,
            34,
        );
        if let Some(version) = self
            .assets
            .optional_pic(&format!("{}.png", view.music.version))?
        {
            overlay(
                image,
                &resize(&version, 183, 90, FilterType::Lanczos3),
                295,
                205,
            );
        }
        let generation = if view.generation == ChartGeneration::Standard {
            "SD.png"
        } else {
            "DX.png"
        };
        overlay(
            image,
            &resize(&self.assets.pic(generation)?, 55, 20, FilterType::Lanczos3),
            350,
            560,
        );
        // ab_glyph and Pillow use different scale units; these values preserve
        // the visible glyph bounds of the former Pillow renderer.
        let artist = fit_text(&view.music.artist, 330, 17.25, &self.assets.bold);
        centered_text(image, (255, 595), &artist, 17.25, INK, &self.assets.bold);
        let title = fit_text(&view.music.title, 420, 26.0, &self.assets.bold);
        centered_text(image, (255, 622), &title, 26.0, INK, &self.assets.bold);
        centered_text(
            image,
            (160, 720),
            &view
                .music
                .display_id
                .map_or_else(String::new, |id| id.to_string()),
            26.0,
            INK,
            &self.assets.regular,
        );
        centered_text(
            image,
            (380, 720),
            &view
                .music
                .bpm
                .map_or_else(|| "-".to_owned(), |bpm| bpm.to_string()),
            26.0,
            INK,
            &self.assets.regular,
        );
        Ok(())
    }

    fn draw_rows(&self, image: &mut RgbaImage, view: &MusicScoreView) -> Result<(), RenderError> {
        for (index, row) in view.rows.iter().enumerate() {
            self.draw_row(image, row, index)?;
        }
        if !view.is_utage() && view.rows.len() == 4 {
            centered_text(
                image,
                (800, 702),
                "没有该难度",
                43.0,
                INK,
                &self.assets.bold,
            );
        }
        Ok(())
    }

    fn draw_row(
        &self,
        image: &mut RgbaImage,
        row: &MusicScoreRow,
        index: usize,
    ) -> Result<(), RenderError> {
        let y = row_y(index);
        overlay(
            image,
            &self
                .assets
                .pic(&format!("d-{}.png", difficulty_index(row.difficulty)))?,
            650,
            i64::from(y),
        );
        centered_text(
            image,
            (685, y + 13),
            &row.constant.map_or_else(|| "-".to_owned(), format_constant),
            29.25,
            WHITE,
            &self.assets.regular,
        );
        if !row.played {
            centered_text(image, (800, y + 67), "未游玩", 43.0, INK, &self.assets.bold);
            return Ok(());
        }
        overlay(
            image,
            &self.assets.pic("ra-dx.png")?,
            850,
            i64::from(y + 37),
        );
        overlay(image, &self.assets.pic("fcfs.png")?, 965, i64::from(y + 30));
        if let Some(grade) = row.grade.as_deref().and_then(rank_asset)
            && let Some(icon) = self.assets.optional_pic(grade)?
        {
            overlay(
                image,
                &resize(&icon, 100, 45, FilterType::Lanczos3),
                737,
                i64::from(y + 37),
            );
        }
        if let Some(combo) = row.combo
            && let Some(icon) = self.assets.optional_pic(combo_asset(combo))?
        {
            overlay(
                image,
                &resize(&icon, 65, 65, FilterType::Lanczos3),
                960,
                i64::from(y + 26),
            );
        }
        if let Some(sync) = row.sync
            && let Some(icon) = self.assets.optional_pic(sync_asset(sync))?
        {
            overlay(
                image,
                &resize(&icon, 65, 65, FilterType::Lanczos3),
                1_025,
                i64::from(y + 26),
            );
        }
        middle_left_text(
            image,
            (510, y + 57),
            &row.achievement
                .map_or_else(|| "-.----%".to_owned(), format_play_achievement),
            49.5,
            INK,
            &self.assets.regular,
        );
        centered_text(
            image,
            (915, y + 48),
            &row.rating
                .map_or_else(|| "-".to_owned(), |value| value.to_string()),
            21.25,
            INK,
            &self.assets.regular,
        );
        if let Some(score) = row.dx_score {
            let theory = row
                .theoretical_dx_score()
                .map_or_else(|| "-".to_owned(), |value| value.to_string());
            centered_text(
                image,
                (916, y + 69),
                &format!("{score}/{theory}"),
                15.5,
                INK,
                &self.assets.regular,
            );
        }
        Ok(())
    }

    fn cover(&self, view: &MusicScoreView) -> Result<(RgbaImage, bool), RenderError> {
        match self
            .covers
            .resolve_music(view.music.cover_value(), view.music.image_name.as_deref())?
        {
            ResolvedCover::Image(image) => Ok((image, false)),
            ResolvedCover::Missing(_) => Ok((
                self.assets
                    .placeholder_cover()?
                    .unwrap_or_else(|| RgbaImage::from_pixel(300, 300, Rgba([224, 229, 245, 255]))),
                true,
            )),
        }
    }
}

pub(super) const fn row_y(index: usize) -> i32 {
    ROW_TOP + index as i32 * ROW_HEIGHT as i32
}

#[cfg(test)]
pub(super) fn row_bounds(index: usize) -> (i32, i32, u32, u32) {
    (ROW_X, row_y(index), ROW_WIDTH, ROW_HEIGHT)
}

fn middle_left_text(
    image: &mut RgbaImage,
    center: (i32, i32),
    text: &str,
    size: f32,
    color: Rgba<u8>,
    font: &FontArc,
) {
    draw_text(
        image,
        (center.0, middle_origin_y(center.1, text, size, font)),
        text,
        size,
        color,
        font,
    );
}

fn centered_text(
    image: &mut RgbaImage,
    center: (i32, i32),
    text: &str,
    size: f32,
    color: Rgba<u8>,
    font: &FontArc,
) {
    let (width, _) = text_size(size, font, text);
    draw_text(
        image,
        (
            center.0 - i32::try_from(width).unwrap_or(i32::MAX) / 2,
            middle_origin_y(center.1, text, size, font),
        ),
        text,
        size,
        color,
        font,
    );
}

fn genre_asset(value: &str) -> &'static str {
    let value = value.to_ascii_lowercase();
    if value.contains("anime") || value.contains("动漫") {
        "anime"
    } else if value.contains("niconico") || value.contains("vocaloid") {
        "niconico"
    } else if value.contains("touhou") || value.contains("东方") {
        "touhou"
    } else if value.contains("ongeki") || value.contains("中二") || value.contains("音击") {
        "ongeki"
    } else if value.contains("game") || value.contains("游戏") {
        "game"
    } else {
        "maimai"
    }
}

fn rank_asset(value: &str) -> Option<&'static str> {
    match value.trim().to_ascii_lowercase().as_str() {
        "d" => Some("UI_TTR_Rank_D.png"),
        "c" => Some("UI_TTR_Rank_C.png"),
        "b" => Some("UI_TTR_Rank_B.png"),
        "bb" => Some("UI_TTR_Rank_BB.png"),
        "bbb" => Some("UI_TTR_Rank_BBB.png"),
        "a" => Some("UI_TTR_Rank_A.png"),
        "aa" => Some("UI_TTR_Rank_AA.png"),
        "aaa" => Some("UI_TTR_Rank_AAA.png"),
        "s" => Some("UI_TTR_Rank_S.png"),
        "s+" | "sp" => Some("UI_TTR_Rank_Sp.png"),
        "ss" => Some("UI_TTR_Rank_SS.png"),
        "ss+" | "ssp" => Some("UI_TTR_Rank_SSp.png"),
        "sss" => Some("UI_TTR_Rank_SSS.png"),
        "sss+" | "sssp" => Some("UI_TTR_Rank_SSSp.png"),
        _ => None,
    }
}

const fn combo_asset(value: FullComboStatus) -> &'static str {
    match value {
        FullComboStatus::FullCombo => "UI_CHR_PlayBonus_FC.png",
        FullComboStatus::FullComboPlus => "UI_CHR_PlayBonus_FCp.png",
        FullComboStatus::AllPerfect => "UI_CHR_PlayBonus_AP.png",
        FullComboStatus::AllPerfectPlus => "UI_CHR_PlayBonus_APp.png",
    }
}

const fn sync_asset(value: FullSyncStatus) -> &'static str {
    match value {
        FullSyncStatus::Sync => "UI_CHR_PlayBonus_Sync.png",
        FullSyncStatus::FullSync => "UI_CHR_PlayBonus_FS.png",
        FullSyncStatus::FullSyncPlus => "UI_CHR_PlayBonus_FSp.png",
        FullSyncStatus::FullSyncDeluxe => "UI_CHR_PlayBonus_FSD.png",
        FullSyncStatus::FullSyncDeluxePlus => "UI_CHR_PlayBonus_FSDp.png",
    }
}

const fn difficulty_index(value: Difficulty) -> usize {
    match value {
        Difficulty::Basic | Difficulty::Utage => 0,
        Difficulty::Advanced => 1,
        Difficulty::Expert => 2,
        Difficulty::Master => 3,
        Difficulty::ReMaster => 4,
    }
}

fn encode(
    image: RgbaImage,
    used_placeholder_cover: bool,
) -> Result<MusicScoreRenderedPng, RenderError> {
    let mut bytes = Vec::new();
    PngEncoder::new(Cursor::new(&mut bytes))
        .write_image(image.as_raw(), WIDTH, HEIGHT, ColorType::Rgba8.into())
        .map_err(RenderError::PngEncode)?;
    Ok(MusicScoreRenderedPng {
        bytes,
        width: WIDTH,
        height: HEIGHT,
        used_placeholder_cover,
    })
}
