use std::{error::Error, path::PathBuf};

use image::ImageReader;
use maimai_core::{
    AchievementRate, ChartConstant, ChartGeneration, Difficulty, FullComboStatus, FullSyncStatus,
};

use super::{MusicScoreRenderer, MusicScoreRow, MusicScoreView};
use crate::{MusicInfoView, SourceSongId};

#[test]
fn normal_and_utage_rows_keep_layout_inside_canvas() {
    for index in 0..5 {
        let (x, y, width, height) = super::renderer::row_bounds(index);
        assert!(y >= 0);
        assert!(y + i32::try_from(height).unwrap_or(i32::MAX) <= 900);
        assert!(x + i32::try_from(width).unwrap_or(i32::MAX) <= 1_200);
    }
    assert!(super::renderer::row_y(0) + 100 <= 900);
}

#[test]
fn renders_fixed_png_for_five_rows_and_single_utage() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../maimaidx_render_mcp/static");
    let temp = tempfile::tempdir()?;
    let renderer = MusicScoreRenderer::new(root, temp.path())?;
    assert_eq!(
        renderer.credit_text(),
        "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by 铃"
    );
    let normal = renderer.render(&view(ChartGeneration::Deluxe, normal_rows()?)?)?;
    assert_eq!((normal.width, normal.height), (1_200, 900));
    let decoded = ImageReader::new(std::io::Cursor::new(&normal.bytes))
        .with_guessed_format()?
        .decode()?;
    assert_eq!((decoded.width(), decoded.height()), (1_200, 900));
    let decoded = decoded.to_rgba8();
    let mut white = 0;
    let mut ink = 0;
    for y in 235..270 {
        for x in 650..720 {
            let pixel = decoded.get_pixel(x, y).0;
            white += usize::from(pixel == [255, 255, 255, 255]);
            ink += usize::from(pixel == [124, 129, 255, 255]);
        }
    }
    assert!(white > 30);
    assert_eq!(ink, 0);
    assert_eq!(ink_size(&decoded, (730, 270, 870, 330)), Some((86, 26)));
    assert_eq!(ink_size(&decoded, (500, 555, 725, 620)), Some((190, 29)));
    assert_eq!(ink_size(&decoded, (100, 805, 1_100, 850)), Some((637, 22)));

    let utage = renderer.render(&view(
        ChartGeneration::UtageOnePlayer,
        vec![row(Difficulty::Utage, 0, false)?],
    )?)?;
    assert_eq!((utage.width, utage.height), (1_200, 900));
    Ok(())
}

fn ink_size(
    image: &image::RgbaImage,
    (left, top, right, bottom): (u32, u32, u32, u32),
) -> Option<(u32, u32)> {
    let mut bounds = (u32::MAX, u32::MAX, 0, 0);
    for y in top..bottom {
        for x in left..right {
            if image.get_pixel(x, y).0 != [124, 129, 255, 255] {
                continue;
            }
            bounds.0 = bounds.0.min(x);
            bounds.1 = bounds.1.min(y);
            bounds.2 = bounds.2.max(x);
            bounds.3 = bounds.3.max(y);
        }
    }
    (bounds.0 != u32::MAX).then_some((bounds.2 - bounds.0 + 1, bounds.3 - bounds.1 + 1))
}

fn view(
    generation: ChartGeneration,
    rows: Vec<MusicScoreRow>,
) -> Result<MusicScoreView, Box<dyn Error>> {
    let music = MusicInfoView::new(
        Some(SourceSongId::numeric(
            maimai_core::SongIdNamespace::DivingFish,
            10_835,
        )),
        Some(10_835),
        "Believe the Rainbow",
        "Artist",
        "maimai",
        "PRiSM",
        Some(180),
        Some(ChartGeneration::Deluxe),
        false,
        None,
        Vec::new(),
    )?;
    Ok(MusicScoreView::new(music, generation, rows)?)
}

fn normal_rows() -> Result<Vec<MusicScoreRow>, Box<dyn Error>> {
    [
        Difficulty::Basic,
        Difficulty::Advanced,
        Difficulty::Expert,
        Difficulty::Master,
        Difficulty::ReMaster,
    ]
    .into_iter()
    .enumerate()
    .map(|(index, difficulty)| row(difficulty, 100 + index as u64, index == 3))
    .collect::<Result<_, _>>()
    .map_err(Into::into)
}

fn row(
    difficulty: Difficulty,
    note_total: u64,
    played: bool,
) -> Result<MusicScoreRow, crate::RenderError> {
    MusicScoreRow::new(
        difficulty,
        "13+",
        Some(
            ChartConstant::from_decimal_str("13.7")
                .map_err(|_| crate::RenderError::invalid("test.constant", "invalid constant"))?,
        ),
        note_total,
        played,
        played
            .then(|| AchievementRate::from_decimal_str("100.1234"))
            .transpose()
            .map_err(|_| crate::RenderError::invalid("test.achievement", "invalid rate"))?
            .map(Into::into),
        played.then(|| "SSS+".to_owned()),
        played.then_some(FullComboStatus::AllPerfectPlus),
        played.then_some(FullSyncStatus::FullSyncDeluxePlus),
        played.then_some(300),
        played.then_some(305),
    )
}
