use std::{error::Error, path::PathBuf};

use maimai_app::b50_image::{
    B50ImageService, B50ImageStyle, OutputPolicy, OutputStore, RenderOptions, ResourceDirectories,
    StyleStore,
};
use maimai_core::{
    AchievementRate, ChartConstant, RatingBreakdown, SongIdNamespace, SongIdValue, SourceSongId,
};
use maimai_render::{
    B50View, ChartType, Difficulty as RenderDifficulty, LegacyAssets, LegacyRenderer, PlayerHeader,
    ScoreCard,
};
use time::OffsetDateTime;

fn song(id: u32) -> Option<SourceSongId> {
    Some(SourceSongId::new(
        SongIdNamespace::DivingFish,
        SongIdValue::Numeric(id),
    ))
}

struct CardFixture<'a> {
    id: u32,
    title: &'a str,
    chart_type: ChartType,
    difficulty: RenderDifficulty,
    level: &'a str,
    constant: f64,
    achievements: f64,
    rating: u32,
    grade: &'a str,
    combo: Option<&'a str>,
    sync: Option<&'a str>,
}

macro_rules! card {
    (
        $id:expr, $title:expr, $chart_type:expr, $difficulty:expr, $level:expr,
        $constant:expr, $achievements:expr, $rating:expr, $grade:expr, $combo:expr,
        $sync:expr $(,)?
    ) => {
        build_card(CardFixture {
            id: $id,
            title: $title,
            chart_type: $chart_type,
            difficulty: $difficulty,
            level: $level,
            constant: $constant,
            achievements: $achievements,
            rating: $rating,
            grade: $grade,
            combo: $combo,
            sync: $sync,
        })
    };
}

fn build_card(fixture: CardFixture<'_>) -> Result<ScoreCard, Box<dyn Error>> {
    let CardFixture {
        id,
        title,
        chart_type,
        difficulty,
        level,
        constant,
        achievements,
        rating,
        grade,
        combo,
        sync,
    } = fixture;
    ScoreCard::new(
        song(id),
        title,
        chart_type,
        difficulty,
        level,
        Some(ChartConstant::from_decimal_str(&format!("{constant:.1}"))?),
        Some(AchievementRate::from_decimal_str(&format!(
            "{achievements:.4}"
        ))?),
        rating,
    )?
    .with_markers(
        Some(grade.to_owned()),
        combo.map(str::to_owned),
        sync.map(str::to_owned),
    )
    .map_err(Into::into)
}

fn main() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let static_dir = root.join("maimaidx_render_mcp/static");
    let cover_cache_dir = root.join("data/extracted_music_resources/jackets");
    let output_dir = root.join("outputs/rust-b50-demo");

    let legacy_font = static_dir.join("adobe_simhei.otf");
    let renderer = LegacyRenderer::new(LegacyAssets::new(&legacy_font, &legacy_font))?;

    let service = B50ImageService::new(
        StyleStore::new(
            root.join("outputs/rust-b50-demo/style.json"),
            B50ImageStyle::Yuzu,
        )?,
        OutputStore::new(&output_dir, OutputPolicy::standard())?,
        renderer,
        ResourceDirectories::new(&static_dir, &cover_cache_dir)?,
    );

    let b35 = vec![
        card!(
            109,
            "Grievous Lady",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14",
            14.7,
            100.6031,
            296,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            110,
            "B.B.K.K.B.K.K.",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14+",
            14.9,
            99.8820,
            288,
            "sss",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            117,
            "インフェルノ",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14",
            14.4,
            100.5002,
            289,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            127,
            "PANDORA PARADOXXX",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14",
            14.7,
            100.2011,
            292,
            "sssp",
            Some("fc"),
            Some("fs"),
        )?,
        card!(
            132,
            "AXION",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            100.0666,
            287,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            135,
            "Oshama Scramble!",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.6,
            100.7104,
            294,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            141,
            "Pursuit Of The Truth",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.5,
            100.3432,
            289,
            "sssp",
            None,
            Some("fsd"),
        )?,
        card!(
            146,
            "Falsum Atlantis.",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            99.9000,
            279,
            "sss",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            150,
            "Regulus",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14",
            14.7,
            100.11,
            291,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            157,
            "Alice's Suitcase",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.5,
            100.008,
            285,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            162,
            "Rainy, rainy",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.6,
            100.55,
            293,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            163,
            "スローアライズ",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.5,
            100.221,
            288,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            170,
            "MONOLITH",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14",
            14.4,
            100.0102,
            284,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            171,
            "White World feat. やまもとまなみ",
            ChartType::Standard,
            RenderDifficulty::Master,
            "13+",
            13.9,
            100.889,
            278,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            178,
            "アトラクトライト",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "13+",
            13.8,
            100.5001,
            274,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            185,
            "ミリオン/ワンズ",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.5,
            99.9820,
            285,
            "sss",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            189,
            "Dualive",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            100.2022,
            288,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            192,
            "パラボラ",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.3,
            100.1111,
            284,
            "sssp",
            Some("fc"),
            Some("fs"),
        )?,
        card!(
            198,
            "セツナトリップ",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "13",
            13.5,
            100.606,
            268,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            203,
            "TiamaT:F minor",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14+",
            14.8,
            99.7000,
            286,
            "sss",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            208,
            "初音ミクの消失",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.6,
            100.404,
            291,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            210,
            "ViRTUS",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            100.05,
            285,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            215,
            "contrapasso -paradiso-",
            ChartType::Standard,
            RenderDifficulty::Master,
            "14",
            14.6,
            100.18,
            289,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            219,
            "Cream puff",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            100.09,
            285,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            221,
            "The Universe",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.6,
            100.23,
            290,
            "sssp",
            None,
            Some("fsd"),
        )?,
        card!(
            226,
            "Everlasting Message",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.7,
            100.33,
            292,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            228,
            "Fragrance",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            100.44,
            288,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            232,
            "Link to you",
            ChartType::Standard,
            RenderDifficulty::Master,
            "13+",
            13.9,
            100.77,
            277,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            237,
            "Staring at you",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.5,
            100.1212,
            287,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            240,
            "Astral blizzard",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.4,
            99.9500,
            280,
            "sss",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            244,
            "VOLAQUA",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.5,
            100.0011,
            285,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            247,
            "エンジェル　バスター",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "13+",
            13.7,
            100.8888,
            273,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            250,
            "トリドリ",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "13",
            13.6,
            100.9999,
            272,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            253,
            "Trick Tear",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "13+",
            13.8,
            100.6565,
            275,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            255,
            "Doppelganger",
            ChartType::Standard,
            RenderDifficulty::ReMaster,
            "14",
            14.6,
            100.2626,
            290,
            "sssp",
            None,
            None,
        )?,
    ];

    let b15 = vec![
        card!(
            10038,
            "Cthugha",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.7,
            100.5505,
            294,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            10041,
            "FREEDOM DiVE",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14+",
            14.9,
            99.8500,
            289,
            "sss",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            10045,
            "Alea jacta est!",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14+",
            14.8,
            100.2112,
            292,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            10057,
            "セイクリッド　ルイン",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.6,
            100.4321,
            291,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            10062,
            "キルキルメタル",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.4,
            100.101,
            285,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            10073,
            "Calamity Fortune",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.5,
            100.2468,
            288,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            10089,
            "おこちゃま戦争",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.3,
            100.7777,
            284,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            10098,
            "ＧＩＦＴ",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.5,
            100.3131,
            287,
            "sssp",
            None,
            Some("fsd"),
        )?,
        card!(
            10104,
            "Unlimited Spark",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.6,
            100.6262,
            290,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            10118,
            "BLACK ROSE",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.4,
            100.1717,
            285,
            "sssp",
            Some("fcp"),
            Some("fsd"),
        )?,
        card!(
            10125,
            "超常マイマイン",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "13+",
            13.9,
            100.9999,
            279,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            10133,
            "Lividi",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.5,
            100.0505,
            286,
            "sssp",
            Some("fcp"),
            None,
        )?,
        card!(
            10142,
            "OverRapid",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.4,
            100.3535,
            285,
            "sssp",
            Some("fc"),
            Some("fsd"),
        )?,
        card!(
            10149,
            "Say Abracadabra",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14+",
            14.8,
            100.1111,
            291,
            "sssp",
            Some("fcp"),
            Some("fsdp"),
        )?,
        card!(
            10152,
            "My My My",
            ChartType::Deluxe,
            RenderDifficulty::Master,
            "14",
            14.3,
            100.8989,
            283,
            "sssp",
            Some("fcp"),
            None,
        )?,
    ];

    let b35_sum: u32 = b35.iter().map(|card| card.rating()).sum();
    let b15_sum: u32 = b15.iter().map(|card| card.rating()).sum();

    let view = B50View::new(
        "Rust 重构 · B50 渲染演示",
        PlayerHeader::new("Test Player", Some(660), Some("祭".to_owned()))?,
        RatingBreakdown {
            b35: b35_sum,
            b15: b15_sum,
            total: b35_sum + b15_sum,
        },
        b35,
        b15,
    )?;

    let now = OffsetDateTime::now_utc();
    let saved = service.render(
        &view,
        RenderOptions {
            style: Some(B50ImageStyle::Yuzu),
            output_dir: Some(output_dir.clone()),
            static_dir: Some(static_dir.clone()),
            cover_cache_dir: Some(cover_cache_dir.clone()),
            filename_stem: "demo".to_owned(),
        },
        now,
    )?;
    println!(
        "rendered {}x{} -> {} (draw {:?})",
        saved.rendered.metadata.width,
        saved.rendered.metadata.height,
        saved.image_path.display(),
        saved.draw_elapsed,
    );
    Ok(())
}
