use std::path::Path;

use image::{
    Rgba, RgbaImage,
    imageops::{FilterType, overlay, resize},
};
use maimai_core::{AchievementRate, ChartGeneration, single_song_rating};

use super::{
    assets::MusicInfoAssets,
    layout::{
        center_text, encode, genre_name, level_constant, middle_left_text, render_version,
        rounded_left,
    },
    model::{MusicInfoChart, MusicInfoRenderedPng, MusicInfoView, difficulty_row},
};
use crate::{CoverResolver, RenderError, cover::ResolvedCover, text::fit_text};

const WIDTH: u32 = 1_200;
const HEIGHT: u32 = 1_300;
const INK: Rgba<u8> = Rgba([124, 130, 255, 255]);
const WHITE: Rgba<u8> = Rgba([255, 255, 255, 255]);
const RATING_TARGETS: [&str; 6] = ["100.5", "100", "99.5", "99", "98", "97"];
const CREDIT: &str = "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by 铃";

pub struct MusicInfoRenderer {
    assets: MusicInfoAssets,
    covers: CoverResolver,
}

impl MusicInfoRenderer {
    pub fn new(
        static_root: impl AsRef<Path>,
        cover_cache_root: impl AsRef<Path>,
    ) -> Result<Self, RenderError> {
        let static_root = static_root.as_ref();
        Ok(Self {
            assets: MusicInfoAssets::load(static_root)?,
            covers: CoverResolver::new(static_root, cover_cache_root.as_ref()),
        })
    }

    pub fn render(&self, view: &MusicInfoView) -> Result<MusicInfoRenderedPng, RenderError> {
        if self.assets.background.dimensions() != (WIDTH, HEIGHT) {
            return Err(RenderError::invalid(
                "music.background",
                "must be exactly 1200 by 1300 pixels",
            ));
        }
        let mut image = self.assets.background.clone();
        self.draw_header(&mut image, view)?;
        self.draw_charts(&mut image, view)?;
        center_text(
            &mut image,
            (600, 1_212),
            CREDIT,
            31.5,
            INK,
            &self.assets.bold,
        );
        let (cover, used_placeholder_cover) = self.cover(view)?;
        let cover = rounded_left(&resize(&cover, 280, 280, FilterType::Lanczos3), 17);
        overlay(&mut image, &cover, 110, 180);
        encode(image, used_placeholder_cover)
    }

    fn draw_header(&self, image: &mut RgbaImage, view: &MusicInfoView) -> Result<(), RenderError> {
        self.paste_optional(image, "logo.png", (65, 25), (249, 120))?;
        if view.is_new {
            self.paste_optional(image, "UI_CMN_TabTitle_NewSong.png", (940, 100), (249, 120))?;
        }
        if !view.version.is_empty() {
            self.paste_optional(
                image,
                &format!("{}.png", render_version(&view.version)),
                (800, 370),
                (182, 90),
            )?;
        }
        if let Some(generation) = view.generation {
            let type_asset = if generation == ChartGeneration::Standard {
                "SD.png"
            } else {
                "DX.png"
            };
            self.paste_optional(image, type_asset, (410, 375), (80, 30))?;
        }

        if !view.title.is_empty() {
            let title = fit_text(&view.title, 650, 34.0, &self.assets.bold);
            middle_left_text(image, (405, 220), &title, 34.0, INK, &self.assets.bold);
        }
        if !view.artist.is_empty() {
            let artist = fit_text(&view.artist, 620, 25.0, &self.assets.bold);
            middle_left_text(image, (407, 265), &artist, 25.0, INK, &self.assets.bold);
        }
        if let Some(bpm) = view.bpm.filter(|value| *value > 0) {
            middle_left_text(
                image,
                (460, 330),
                &bpm.to_string(),
                36.0,
                INK,
                &self.assets.regular,
            );
        }
        if let Some(id) = view.display_id.filter(|value| *value > 0) {
            middle_left_text(
                image,
                (405, 435),
                &format!("ID {id}"),
                34.0,
                INK,
                &self.assets.regular,
            );
        }
        let genre = genre_name(&view.genre);
        if !genre.is_empty() {
            center_text(image, (665, 435), genre, 29.0, INK, &self.assets.bold);
        }
        Ok(())
    }

    fn draw_charts(&self, image: &mut RgbaImage, view: &MusicInfoView) -> Result<(), RenderError> {
        for chart in &view.charts {
            let row = difficulty_row(chart.difficulty);
            let y = 600 + 73 * row as i32;
            let level = level_constant(chart);
            if !level.is_empty() {
                center_text(
                    image,
                    (181, y + 10),
                    &level,
                    36.0,
                    WHITE,
                    &self.assets.regular,
                );
            }
            if let Some(fit) = chart.fit_constant {
                center_text(
                    image,
                    (315, y),
                    &format!("{:.2}", fit.value()),
                    36.0,
                    INK,
                    &self.assets.regular,
                );
            }
            self.draw_notes(image, chart, view.generation, y);
            if row >= 2 {
                self.draw_rating_row(image, view, chart, row)?;
            }
        }
        Ok(())
    }

    fn draw_notes(
        &self,
        image: &mut RgbaImage,
        chart: &MusicInfoChart,
        generation: Option<ChartGeneration>,
        y: i32,
    ) {
        let component_total = chart.notes.map_or(0, |notes| notes.total());
        let total = chart
            .note_total
            .map(u64::from)
            .filter(|value| *value > 0)
            .or_else(|| (component_total > 0).then_some(component_total));
        if let Some(total) = total {
            center_text(
                image,
                (437, y),
                &total.to_string(),
                36.0,
                INK,
                &self.assets.regular,
            );
        }
        let Some(notes) = chart.notes.filter(|_| component_total > 0) else {
            return;
        };
        for (index, value) in [
            notes.tap,
            notes.hold,
            notes.slide,
            notes.touch,
            notes.break_notes,
        ]
        .into_iter()
        .enumerate()
        {
            if generation == Some(ChartGeneration::Standard) && index == 3 {
                continue;
            }
            center_text(
                image,
                (556 + 119 * index as i32, y),
                &value.to_string(),
                36.0,
                INK,
                &self.assets.regular,
            );
        }
    }

    fn draw_rating_row(
        &self,
        image: &mut RgbaImage,
        view: &MusicInfoView,
        chart: &MusicInfoChart,
        row: usize,
    ) -> Result<(), RenderError> {
        let y = 1_030 + 47 * (row as i32 - 2);
        if !chart.charter.is_empty() {
            let charter = fit_text(&chart.charter, 205, 22.0, &self.assets.bold);
            center_text(image, (372, y), &charter, 22.0, INK, &self.assets.bold);
        }
        let Some(constant) = chart.constant else {
            return Ok(());
        };
        for (index, achievement) in RATING_TARGETS.into_iter().enumerate() {
            let achievement = AchievementRate::from_decimal_str(achievement)
                .map_err(|_| RenderError::invalid("music.rating_target", "invalid target"))?;
            let rating = single_song_rating(constant, achievement)
                .map_err(|_| RenderError::invalid("music.rating", "calculation overflow"))?;
            let gain = view
                .score_context
                .as_ref()
                .map_or(0, |context| context.gain(chart.difficulty, rating));
            let label = if gain > 0 {
                format!("{rating}(+{gain})")
            } else {
                rating.to_string()
            };
            center_text(
                image,
                (536 + 101 * index as i32, y),
                &label,
                if gain > 0 { 24.0 } else { 30.0 },
                INK,
                &self.assets.regular,
            );
        }
        Ok(())
    }

    fn cover(&self, view: &MusicInfoView) -> Result<(RgbaImage, bool), RenderError> {
        match self
            .covers
            .resolve_music(view.cover_value(), view.image_name.as_deref())?
        {
            ResolvedCover::Image(image) => Ok((image, false)),
            ResolvedCover::Missing(_) if view.require_cover => Err(RenderError::invalid(
                "music.cover",
                "cover-only song has no local cover",
            )),
            ResolvedCover::Missing(_) => Ok((
                self.assets
                    .placeholder_cover()?
                    .unwrap_or_else(|| RgbaImage::from_pixel(280, 280, Rgba([224, 229, 245, 255]))),
                true,
            )),
        }
    }

    fn paste_optional(
        &self,
        image: &mut RgbaImage,
        name: &str,
        at: (i64, i64),
        size: (u32, u32),
    ) -> Result<(), RenderError> {
        if let Some(asset) = self.assets.optional_pic(name)? {
            overlay(
                image,
                &resize(&asset, size.0, size.1, FilterType::Lanczos3),
                at.0,
                at.1,
            );
        }
        Ok(())
    }
}
